DetentionCentre/DetentionCentre/Models/Detainee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DetentionCentre.Models
{
    public class Detainee
    {
        public int DetaineeId { get; set; }

        [Required(ErrorMessage = "Enter last name")]
        [MaxLength(50)]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Enter first name")]
        [MaxLength(50)]
        public string FirstName { get; set; }

        [MaxLength(50)]
        public string MiddleName { get; set; }

        [Required(ErrorMessage = "Indicate date of birth")]
        public DateTime? BirthDate { get; set; }

        [MaxLength(10)]
        public string MaritalStatus { get; set; }

        [Required(ErrorMessage = "Enter work place")]
        [MaxLength(100)]
        public string WorkPlace { get; set; }

        [Required(ErrorMessage = "Enter home adress")]
        [MaxLength(150)]
        public string HomeAdress { get; set; }

        [MaxLength(50)]
        public string PhoneNumber { get; set; }

        [MaxLength(50)]
        public string Photo { get; set; }

        [MaxLength(300)]
        public string Additional { get; set; }

        public IEnumerable<Arrest> Arrests { get; set; }

        public override int GetHashCode()
        {
            return DetaineeId;
        }

        public override bool Equals(object obj)
        {
            var incomingDetainee = obj as Detainee;

            if (this.DetaineeId == incomingDetainee.DetaineeId)
            {
                return true;
            }

            return false;
        }
    }
}

DetentionCentre/DetentionCentre/Controllers/ArrestsController.cs
using DetentionCentre.Models;
using DetentionCentre.Services;
using DetentionCentre.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace DetentionCentre.Controllers
{
    [Authorize(Roles = "Admin, Editor")]
    public class ArrestsController : Controller
    {
        private readonly IDetentionManagementService _detentionService;

        public ArrestsController(IDetentionManagementService detentionService)
        {
            _detentionService = detentionService;
        }

        [HttpGet]
        public IActionResult Add(int detaineeId)
        {
            ViewData["CurrentPage"] = "Home";

            return View("Edit", new ArrestEditViewModel
            {
                DetaineeId = detaineeId,
                Officers = new List<Officer>(),
                AvailableOfficers = _detentionService.GetAvailableOfficers()
            });
        }

        [HttpGet]
        public IActionResult Edit(int arrestId)
        {
            ViewData["CurrentPage"] = "Home";

            var arrest = _detentionService.GetArrestByArrestID(arrestId);

            return View("Edit", new ArrestEditViewModel
            {
                ArrestId = arrest.ArrestId,
                DeliveryDate = arrest.DeliveryDate,
                DetaineeId = arrest.DetaineeId,
                DetentionDate = arrest.DetentionDate,
                DetentionPlace = arrest.DetentionPlace,
                EstimatedAmount = arrest.EstimatedAmount?.ToString("0.00", CultureInfo.InvariantCulture),
                Officers = arrest.Officers.ToList(),
                PaidAmount = arrest.PaidAmount?.ToString("0.00", CultureInfo.InvariantCulture),
                ReleaseDate = arrest.ReleaseDate,

                AvailableOfficers = _detentionService.GetAvailableOfficers(arrest.Officers)
            });
        }

        [HttpGet]
        public IActionResult Delete(int arrestId, int detaineeId)
        {
            _detentionService.DeleteArrestByArrestId(arrestId);

            return RedirectToAction("Details", "Home", new { id = detaineeId });
        }

        [HttpPost]
        public IActionResult SaveChanges(ArrestEditViewModel arrestEditViewModel)
        {
            if (!ModelState.IsValid)
            {
                arrestEditViewModel.AvailableOfficers = _detentionService.GetAvailableOfficers(arrestEditViewModel.Officers);

                return View("Edit", arrestEditViewModel);
            }

            int arrestId;
            decimal? estimatedAmount = null;
            decimal? paidAmount = null;

            if (decimal.TryParse(arrestEditViewModel.EstimatedAmount, NumberStyles.AllowDecimalPoint, CultureInfo.InvariantCulture, out decimal estimatedAmountValue))
            {
                estimatedAmount = estimatedAmountValue;
            }

            if (decimal.TryParse(arrestEditViewModel.PaidAmount, NumberStyles.AllowDecimalPoint, CultureInfo.InvariantCulture, out decimal paidAmountValue))
            {
                paidAmount = paidAmountValue;
            }

            var arrest = new Arrest
            {
                DeliveryDate = arrestEditViewModel.DeliveryDate,
                DetaineeId = arrestEditViewModel.DetaineeId,
                DetentionDate = arrestEditViewModel.DetentionDate,
                DetentionPlace = arrestEditViewModel.DetentionPlace,
                EstimatedAmount = estimatedAmount,
                Officers = arrestEditViewModel.Officers,
                PaidAmount = paidAmount,
                ReleaseDate = arrestEditViewModel.ReleaseDate
            };

            if (arrestEditViewModel.ArrestId.HasValue)
            {
                arrest.ArrestId = arrestEditViewModel.ArrestId.Value;

                var previousOfficersCount = _detentionService.GetLinks(arrest.ArrestId.Value).Count();

                if (previousOfficersCount < arrest.Officers.Count())
                {
                    _detentionService.AddLinks(arrest.ArrestId.Value, arrest.Officers);
                }
                else if (previousOfficersCount > arrest.Officers.Count())
                {
                    _detentionService.DeleteLinks(arrest.ArrestId.Value, arrest.Officers);
                }

                _detentionService.UpdateArrest(arrest);

                arrestId = arrest.ArrestId.Value;
            }
            else
            {
                int newArrestId = _detentionService.InsertArrest(arrest);

                if (arrest.Officers != null)
                {
                    foreach (var officer in arrest.Officers)
                    {
                        _detentionService.InsertOfficerForArrest(officer, newArrestId);
                    }
                }

                arrestId = newArrestId;
            }

            return RedirectToAction("Edit", new { arrestId });
        }

        [HttpPost]
        public IActionResult AddOfficer(ArrestEditViewModel arrestEditViewModel)
        {
            ViewData["CurrentPage"] = "Home";

            List<Officer> officers = new List<Officer>();

            if (arrestEditViewModel.Officers != null)
            {
                officers = arrestEditViewModel.Officers.ToList();
            }

            if (arrestEditViewModel.SelectedOfficerId.HasValue)
            {
                var selectedOfficer = _detentionService.GetOfficerById(arrestEditViewModel.SelectedOfficerId.Value);

                officers.Add(selectedOfficer);

                arrestEditViewModel.Officers = officers;
            }

            arrestEditViewModel.AvailableOfficers = _detentionService.GetAvailableOfficers(arrestEditViewModel.Officers);
            arrestEditViewModel.SelectedOfficerId = null;

            return View("Edit", arrestEditViewModel);
        }

        [HttpPost]
        public IActionResult RemoveOfficer(ArrestEditViewModel arrestEditViewModel, int id)
        {
            ViewData["CurrentPage"] = "Home";

            var officer = arrestEditViewModel.Officers.FirstOrDefault(f => f.OfficerId == id);

            if (officer != null)
            {
                arrestEditViewModel.Officers.Remove(officer);
                arrestEditViewModel.AvailableOfficers = _detentionService.GetAvailableOfficers(arrestEditViewModel.Officers);
                arrestEditViewModel.SelectedOfficerId = null;
            }

            return View("Edit", arrestEditViewModel);
        }
    }
}

DetentionCentre/DetentionCentre/Controllers/HomeController.cs
using DetentionCentre.Models;
using DetentionCentre.Services;
using DetentionCentre.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;

namespace DetentionCentre.Controllers
{
    public class HomeController : Controller
    {
        private const string PhotosFolderName = "photos";

        private readonly IDetentionManagementService _detentionService;
        private readonly IWebHostEnvironment _appEnvironment;
        private readonly ILogger _logger;

        public HomeController(
            IWebHostEnvironment env,
            IDetentionManagementService detentionManagementService,
            ILogger<HomeController> logger)
        {
            _detentionService = detentionManagementService;
            _appEnvironment = env;
            _logger = logger;
        }

        [Authorize(Roles = "Admin, Editor, Guest")]
        public IActionResult Index()
        {
            ViewData["CurrentPage"] = "Home";

            var detainees = _detentionService.GetDetainees();

            return View(detainees);
        }

        [Authorize(Roles = "Admin, Editor, Guest")]
        [HttpGet]
        public IActionResult Details(int? id)
        {
            ViewData["CurrentPage"] = "Home";

            if (id == null)
            {
                return RedirectToAction("Index");
            }

            Detainee detainee = _detentionService.GetDetaineeById(id.Value);

            return View(detainee);
        }

        [Authorize(Roles = "Admin, Editor")]
        [HttpPost]
        public async Task<IActionResult> AddFile(FileUploadViewModel file)
        {
            if (file.UploadedFile != null)
            {
                var photoDirectoryPath = Path.Combine(_appEnvironment.WebRootPath, PhotosFolderName);

                if (!Directory.Exists(photoDirectoryPath))
                {
                    Directory.CreateDirectory(photoDirectoryPath);
                }

                var uploadedFileExtension = Path.GetExtension(file.UploadedFile.FileName);

                var fileName = $"{file.DetaineeId}{uploadedFileExtension}";

                using (var fileStream = new FileStream(Path.Combine(photoDirectoryPath, fileName), FileMode.Create))
                {
                    await file.UploadedFile.CopyToAsync(fileStream);
                }

                _detentionService.UpdatePhoto(file.DetaineeId, $"/{PhotosFolderName}/{fileName}");
            }

            return RedirectToAction("Details", new { id = file.DetaineeId });
        }

        [Authorize(Roles = "Admin, Editor")]
        [HttpPost]
        public IActionResult EditPersonalInformation(Detainee detainee)
        {
            ViewData["CurrentPage"] = "Home";

            if (ModelState.IsValid)
            {
                _detentionService.UpdateDetaineeInformation(detainee);

                return RedirectToAction("Details", new { id = detainee.DetaineeId });
            }

            return View("Details", detainee);
        }

        [Authorize(Roles = "Admin, Editor")]
        [HttpGet]
        public IActionResult AddDetainee()
        {
            ViewData["CurrentPage"] = "AddDetainee";

            return View("Detainee", new Detainee());
        }

        [Authorize(Roles = "Admin, Editor")]
        [HttpPost]
        public IActionResult CreateDetainee(Detainee detainee)
        {
            ViewData["CurrentPage"] = "AddDetainee";

            if (ModelState.IsValid)
            {
                var newDetaineeId = _detentionService.CreateDetainee(detainee);

                return RedirectToAction("Details", new { id = newDetaineeId });
            }

            return View("Detainee", detainee);
        }

        [Authorize(Roles = "Admin, Editor")]
        [HttpGet]
        public IActionResult DeleteDetainee(int id)
        {
            _detentionService.DeleteDetaineeById(id, Path.Combine(_appEnvironment.WebRootPath, PhotosFolderName));

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var path = HttpContext
              .Features
              .Get<IExceptionHandlerPathFeature>();
 
            var exception = path.Error;
            var pathString = path.Path;

            _logger.LogError(exception.Message);

            return View("../Shared/Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DetentionCentre/DetentionCentre/Views/Home/Details.cshtml
@model Detainee
@{ Layout = "_Layout"; }

<h1>Personal information</h1>

<div class="detainee-edit-form">
    <form asp-action="EditPersonalInformation" asp-controller="Home" method="post">
        <table class="edit-form-table">
            <tr>
                <th scope="row">ID</th>
                <td>
                    @Model.DetaineeId
                    <input type="number" name="DetaineeId" value="@Model.DetaineeId" hidden />
                </td>
            </tr>
            <tr>
                <th scope="row">Last name</th>
                <td>
                    <input type="text" name="LastName" asp-for="LastName" maxlength="50" size="65" />
                    <span asp-validation-for="LastName"></span>
                </td>
            </tr>
            <tr>
                <th scope="row">First name</th>
                <td>
                    <input type="text" name="FirstName" asp-for="FirstName" maxlength="50" size="65" />
                    <span asp-validation-for="FirstName"></span>
                </td>
            </tr>
            <tr>
                <th scope="row">Middle name</th>
                <td>
                    <input type="text" name="MiddleName" asp-for="MiddleName" maxlength="50" size="65" />
                </td>
            </tr>
            <tr>
                <th scope="row">Birth date</th>
                <td>
                    <input type="date" name="BirthDate" asp-for="BirthDate" asp-format="{0:yyyy-MM-dd}" size="65" />
                    <span asp-validation-for="BirthDate"></span>
                </td>
            </tr>
            <tr>
                <th scope="row">Marital status</th>
                <td>
                    <input type="text" name="MaritalStatus" asp-for="MaritalStatus" maxlength="10" size="65" />
                </td>
            </tr>
            <tr>
                <th scope="row">Work place</th>
                <td>
                    <input type="text" name="WorkPlace" asp-for="WorkPlace" maxlength="100" size="65" />
                    <span asp-validation-for="WorkPlace"></span>
                </td>
            </tr>
            <tr>
                <th scope="row">Home adress</th>
                <td>
                    <input type="text" name="HomeAdress" asp-for="HomeAdress" maxlength="150" size="65" />
                    <span asp-validation-for="HomeAdress"></span>
                </td>
            </tr>
            <tr>
                <th scope="row">Phone number</th>
                <td>
                    <input type="text" name="PhoneNumber" asp-for="PhoneNumber" maxlength="50" size="65" />
                </td>
            </tr>
            <tr>
                <th scope="row">Additional</th>
                <td>
                    <input type="text" name="Additional" asp-for="Additional" maxlength="300" size="65" />
                </td>
            </tr>
        </table>

        @if (User.IsInRole("Admin") || User.IsInRole("Editor"))
        {
            <div class="detainee-edit-panel">
                <input class="green-btn" type="submit" value="Save changes" />
                <input class="green-btn" type="button" value="Delete detainee" onclick="location.href = '@Url.Action("DeleteDetainee", "Home", new {id = Model.DetaineeId})'" />
                <input class="green-btn" type="button" value="Add arrest" onclick="location.href = '@Url.Action("Add", "Arrests", new {detaineeID = Model.DetaineeId})'" />
            </div>
        }

        <input type="hidden" value="@Model.Photo" asp-for="Photo" />
        <input type="hidden" value="@Model.Arrests" asp-for="Arrests" />
    </form>

    <div class="file-upload">
        <img src="@Model.Photo" alt="Detainee photo" width="300" height="400">

        @if (User.IsInRole("Admin") || User.IsInRole("Editor"))
        {
            <form asp-action="AddFile" asp-controller="Home" method="post" enctype="multipart/form-data">
                <input type="hidden" asp-for="DetaineeId" value="@Model.DetaineeId" />

                <input class="custom-file-input"
                       style="opacity: 1 !important;"
                       type="file"
                       name="uploadedFile"
                       accept="image/*" />
                <br>
                <input class="uploadButton" type="submit" value="Upload" />
            </form>
        }
    </div>
</div>

<div id="arrests-table">
    <h1>Arrests</h1>

    <table class="bordered-table">

        <tr>
            <th scope="col" width="85px" height="30px">Arrest ID</th>
            <th scope="col" width="150px" height="30px">Detention date</th>
            <th scope="col" width="150px" height="30px">Delivery date</th>
            <th scope="col" width="150px" height="30px">Release date</th>
            <th scope="col" width="150px" height="30px">Detention place</th>
            <th scope="col" width="135px" height="30px">Estimated amount</th>
            <th scope="col" width="110px" height="30px">Paid amount</th>
            <th scope="col" width="320px" height="30px">Officers</th>

            @if (User.IsInRole("Admin") || User.IsInRole("Editor"))
            {
                <th scope="col" width="85px" height="30px" colspan="2">Actions</th>
            }
        </tr>

        @foreach (var arrest in Model.Arrests)
        {
            <tr>
                <td>@arrest.ArrestId</td>
                <td>@arrest.DetentionDate</td>
                <td>@arrest.DeliveryDate</td>
                <td>@arrest.ReleaseDate</td>
                <td>@arrest.DetentionPlace</td>
                <td>@arrest.EstimatedAmount?.ToString("0.00")</td>
                <td>@arrest.PaidAmount?.ToString("0.00")</td>
                <td>
                    @foreach (var officer in arrest.Officers)
                    {
                        <p>@officer.FirstName @officer.LastName @officer.MiddleName [@officer.Title]</p>
                    }
                </td>

                @if (User.IsInRole("Admin") || User.IsInRole("Editor"))
                {
                    <td width="30px">
                        <a href='@Url.Action("Edit", "Arrests", new { arrestId = @arrest.ArrestId, detaineeId = @Model.DetaineeId})'>Edit</a>
                    </td>
                    <td width="30px">
                        <a href='@Url.Action("Delete", "Arrests", new { arrestId = @arrest.ArrestId, detaineeId = Model.DetaineeId})'>Remove</a>
                    </td>
                }
            </tr>
        }
    </table>
</div>

DetentionCentre/DetentionCentre/Views/Home/Detainee.cshtml
@model Detainee
@{
    Layout = "_Layout";
}


<h1>Personal information</h1>
<div class="detainee-edit-form">
    <form asp-action="CreateDetainee" asp-controller="Home" method="post">
        <table class="edit-form-table">
            @if (Model.DetaineeId != 0)
            {
                <tr>
                    <th scope="row">ID</th>
                    <td>
                        @Model.DetaineeId
                        <input type="number" name="DetaineeId" value="@Model.DetaineeId" hidden />
                    </td>
                </tr>
            }
            <tr>
                <th scope="row">Last name</th>
                <td>
                    <input type="text" name="LastName" asp-for="LastName" maxlength="50" size="65" />
                    <span asp-validation-for="LastName"></span>
                </td>
            </tr>
            <tr>
                <th scope="row">First name</th>
                <td>
                    <input type="text" name="FirstName" asp-for="FirstName" maxlength="50" size="65" />
                    <span asp-validation-for="FirstName"></span>
                </td>
            </tr>
            <tr>
                <th scope="row">Middle name</th>
                <td>
                    <input type="text" name="MiddleName" asp-for="MiddleName" maxlength="50" size="65" />
                </td>
            </tr>
            <tr>
                <th scope="row">Birth date</th>
                <td>
                    <input type="date" name="BirthDate" asp-for="BirthDate" asp-format="{0:yyyy-MM-dd}" size="65" />
                    <span asp-validation-for="BirthDate"></span>
                </td>
            </tr>
            <tr>
                <th scope="row">Marital status</th>
                <td>
                    <input type="text" name="MaritalStatus" asp-for="MaritalStatus" maxlength="10" size="65" />
                </td>
            </tr>
            <tr>
                <th scope="row">Work place</th>
                <td>
                    <input type="text" name="WorkPlace" asp-for="WorkPlace" maxlength="100" size="65" />
                    <span asp-validation-for="WorkPlace"></span>
                </td>
            </tr>
            <tr>
                <th scope="row">Home adress</th>
                <td>
                    <input type="text" name="HomeAdress" asp-for="HomeAdress" maxlength="150" size="65" />
                    <span asp-validation-for="HomeAdress"></span>
                </td>
            </tr>
            <tr>
                <th scope="row">Phone number</th>
                <td>
                    <input type="text" name="PhoneNumber" asp-for="PhoneNumber" maxlength="50" size="65" />
                </td>
            </tr>
            <tr>
                <th scope="row">Additional</th>
                <td>
                    <input type="text" name="Additional" asp-for="Additional" maxlength="300" size="65" />
                </td>
            </tr>
        </table>
        <div class="detainee-edit-panel">
            <input class="green-btn" type="submit" value="Add Detainee" />
        </div>
    </form>
</div>

DetentionCentre/DetentionCentre/Views/Home/Index.cshtml
@model IEnumerable<Detainee>
@{
    ViewData["Title"] = "List of detaines";
    Layout = "_Layout";
}


<table class="bordered-table">
    <tr>
        <th>Id</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Middle name</th>
        <th>More information</th>
    </tr>

    @foreach (var detainee in Model)
    {
        <tr>
            <td>@detainee.DetaineeId</td>
            <td>@detainee.FirstName</td>
            <td>@detainee.LastName</td>
            <td>@detainee.MiddleName</td>
            <td>
                <a href="/Home/Details/@detainee.DetaineeId">Details</a>
            </td>
        </tr>
    }
</table>